### ISSUE TITLE
UTF-8 encoding of response

### ISSUE THREAD

**Issue by si14** [bbengfort/django-generic-json-views#11]
Hello there and thanks for a nice library!

There is a little mishap: if encoded JSON happens to contain UTF-8, it become garbled with some clients. This is because ideally `Content-Type` should contain `charset=utf-8`, too.

**Comment by bbengfort** [comment]
Hi @si14 - thanks for reporting the bug. Would you mind providing some code/a test case that produces the error you're referring to? Given the test case, I can write the test, make the fix and then push it to the repo (and I could probably do a hotfix here). 

Of course, you're also more than welcome to submit a pull request with a fix and tests.

**Comment by si14** [comment]
Here is a simple example. Let's take this simple view (assuming the file uses utf-8 encoding itself):

```python
class JSONUtfView(JSONDataView):
    def get_context_data(self, **kwargs):
        context = super(JSONUtfView, self).get_context_data(**kwargs)
        context['test'] = u"Привет"
        return context
```

If you then open the corresponding URL in Chrome with this https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en plugin, JSON will be garbled because of wrong encoding.

It's not an issue of JSONDataView itself, it's a display issue, but it can be easily solved by explicit encoding.

**Comment by bbengfort** [comment]
Ok, just pushed some code, on your view you can now set the following class variables:

- mimetype = "application/json"
- format   = "json"
- encoding = "utf-8"

```python
class JSONUtfView(JSONDataView):
    
    encoding  = "utf-8"
    mimetype = "application/json" 

    def get_context_data(self, **kwargs):
        context = super(JSONUtfView, self).get_context_data(**kwargs)
        context['test'] = u"Привет"
        return context
```

These are the defaults, but this is just for illustration. 

Now the Content-Type will be:

    self.assertEqual(response['Content-Type'], 'application/json; charset=utf-8')

Hope that helps solve your problem.
