### ISSUE TITLE
Submit to PYPI

### ISSUE THREAD

**Issue by sidmitra** [bbengfort/django-generic-json-views#3]
This is a useful module and would be good to have this in pypi.

https://pypi.python.org/pypi

**Comment by sidmitra** [comment]
Also 
http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by bbengfort** [comment]
I appreciate that, and am glad you think it's useful. However, I think that if you're writing Django APIs, there are much more useful tools for JSON serialization, specifically [Django Rest Framework](http://www.django-rest-framework.org/). 

Additionally, the JSON serializer is an example in the Django documentation - [JSON Response Mixin](https://docs.djangoproject.com/en/1.7/topics/class-based-views/mixins/#jsonresponsemixin-example).

Hopefully those links help you with your development problem, but if you have any other use cases for these classes, then I suppose I would be happy to write tests for it and submit it to PyPI.

**Comment by sidmitra** [comment]
Thanks for the quick reply! I found your library pretty good for those quick fix solutions or mixins where you're just have a few views that handle json, but not entirely a rest API. I found it fairly useful to just inherit some of your classes rather than re-write some of the same base classes myself.

**Comment by bbengfort** [comment]
See Issue #4

**Comment by bbengfort** [comment]
Ok, you got it - it's now on PyPI - but there's still a lot of work to be done! Feel free to take on any of the issues on Waffle.io and help make this a little better!

**Comment by sidmitra** [comment]
Great. Thanks a lot.
